// Generated by `bun init`

declare module "bun:bundle" {
  interface Registry {
    features: "IS_DEV" | "SSR";
  }
}

declare module "bun" {
  interface Env {
    ASSETS_CACHE_MAX_AGE: string;
    COMPRESSION_ENABLED: string;
    PUBLIC_DEFAULT_TITLE: string;
  }
}

type ColorScheme = "light" | "dark" | "default";

var colorScheme: {
  storageKey: string;
  initialValue: "default";
  mql: () => MediaQueryList | undefined;
  getCalculated: () => ColorScheme;
  getPreferred: () => ColorScheme;
  apply: (value: ColorScheme) => void;
  initListeners: () => void;
};

declare module "*.css?inline" {
  /**
   * A string containing the CSS style
   */
  const style: string;
  export = style;
}

declare module "*.css" {
  /**
   * A path to the CSS file
   */
  const path: `${string}.css`;
  export = path;
}

declare module "*.svg" {
  const path: `${string}.svg`;
  export = path;
}

declare module "*.module.css" {
  /**
   * A record of class names to their corresponding CSS module classes
   */
  const classes: { readonly [key: string]: string };
  export = classes;
}

declare module "*.avif" {
  const path: `${string}.avif`;
  export = path;
}
