// Generated by `bun init`

declare module "bun:bundle" {
  interface Registry {
    features: "IS_DEV" | "SSR";
  }
}

declare module "bun" {
  interface Env {
    PORT: string;
    ASSETS_CACHE_MAX_AGE: string;
    COMPRESSION: "ENABLED" | "DISABLED";
    PUBLIC_DEFAULT_TITLE: string;
  }
}

type ColorScheme = "light" | "dark" | "default";

var colorScheme: {
  storageKey: string;
  initialValue: "default";
  mql: () => MediaQueryList | undefined;
  getCalculated: () => ColorScheme;
  getPreferred: () => ColorScheme;
  apply: (value: ColorScheme) => void;
  initListeners: () => void;
};

declare module "*?inline" {
  /**
   * A string containing the contents of the file
   */
  const content: string;
  export = content;
}

declare module "*?dataurl" {
  /**
   * A string containing the contents of the file as data url
   */
  const dataurl: string;
  export = dataurl;
}

declare module "*.svg" {
  const path: `${string}.svg`;
  export = path;
}

declare module "*.avif" {
  const path: `${string}.avif`;
  export = path;
}

declare module "*.module.css" {
  /**
   * A record of class names to their corresponding CSS module classes
   */
  const classes: { readonly [key: string]: string };
  export = classes;
}
